### ISSUE TITLE
\Drupal\content_entity_base\Entity\Views\EntityBaseViewsData could be useful

### ISSUE THREAD

**Issue by dawehner** [fago/entity#25]
It would be nice to have `\Drupal\content_entity_base\Entity\Views\EntityBaseViewsData` as part of entity module. Many revisionable entities need to have something like that.

TODO: Ideally we would also have some related core issue for that as well

**Comment by dawehner** [comment]
https://www.drupal.org/node/2630886 is the appropriate core issues

**Comment by Jaesin** [comment]
The D.O. issue has been committed. Nice work.

**Comment by dawehner** [comment]
It even got committed to 8.0.x, so I guess we just remove the bit from content_entity_base itself, once the next stable version of 8.0.x is released?
