### ISSUE TITLE
Plan for a time after core 8.1.x

### ISSUE THREAD

**Issue by dawehner** [fago/entity#30]
How should entity module be structured once 8.1.x is out?

**Comment by dawehner** [comment]
Idea: Tag a release 8.x-1.0 for example and continue to work on 8.x-2.0 along with 8.x-2.x. Everything which is in core 8.1.x could be removed from 8.x-2.x then.

**Comment by Berdir** [comment]
Something like that yes. 1.0 might be confusing when you have 8.1.0 then then need 8.x-2.x for that? Maybe we should skip a release, we don't have something "stable" yet anyway. afaik, d.o also allows "weird" versions like 8.x-0.x? haven't tried yet, though.

**Comment by dawehner** [comment]
Good point. I would vote to indeed go with 8.x-0.x and in case this doesn't work, at least document it properly in the readme which version is compatible with which version of core.

**Comment by bojanz** [comment]
Works for me.

Once 8.1 get frozen we branch 8.x-0.x, and remove any committed classes from 8.x-1.x

**Comment by fago** [comment]
Yes, I already suggested the 0.x approach as well, so +1 on doing that.

> Once 8.1 get frozen we branch 8.x-0.x, and remove any committed classes from 8.x-1.x

sounds like a plan!

**Comment by heddn** [comment]
Right now entity module HEAD is broken with 8.2.x core HEAD because http://drupal.org/node/2666792 landed.

**Comment by bojanz** [comment]
I've branched 8.x-1.x into 8.x-0.x and pushed the new branch to GitHub and d.o

Opened a PR for rebasing on latest core: #38. We need to get that merged, then tag 1.0-alpha2, along with a dev release for 8.x-0.x

EDIT: Created the -dev release for 8.x-0.x

**Comment by charlotte17** [comment]
Not having an 8.0.x version on https://packagist.drupal-composer.org/packages/drupal/entity is throwing errors right now with composer_manager.

**Comment by bojanz** [comment]
The PR has been merged, 8.x-1.x now works with Drupal 8.1.x.
Alpha2 coming soon.

Meanwhile, I've tagged 8.x-0.1: https://www.drupal.org/node/2696443
