### ISSUE TITLE
"Revision log message" form field shows up twice.

### ISSUE THREAD

**Issue by Jaesin** [fago/entity#34]
On the `/entity_test_enhanced/add/second` entity add form, the "Revision log message" form shows up twice. 

Producing "Double revision vision" by chance.

**Comment by dawehner** [comment]
Do you mind creating a PR for that, to fix the form to simply not create a manual form for the revision log?

**Comment by bradjones1** [comment]
Was writing this up at d.o. when I found this issue. https://www.drupal.org/node/2765075
