### ISSUE TITLE
No operations available on /entity_test_enhanced/

### ISSUE THREAD

**Issue by Jaesin** [fago/entity#35]
The content listing page gives an empty table. 

I understand there are no base fields for the test entity at this point but shouldn't operations at lease be visible?

<img width="614" alt="screen shot 2016-03-01 at 12 00 27 am" src="https://cloud.githubusercontent.com/assets/159693/13421090/ad43a13e-df40-11e5-9a78-f79fa378da12.png">

**Comment by dawehner** [comment]
Mh, good question. Isn't that controlled by access checking, see `\Drupal\Core\Entity\EntityListBuilder::getDefaultOperations`?
